---
title: "RAIS 2010"
description: |
  Análise da base de dados RAIS do ano de 2010.
author: 
  - name: Rafael Peixoto
    affiliation: Universidade Estadual de Campinas
date: 09-15-2021
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(tidyverse)
library(rmarkdown)
library(ggthemes)
```

# Importação dos dados

```{r}
RR10 <- fread(
  file = "RR2010.txt",
  header = TRUE,
  sep = ";",
  dec = ",",
  encoding = "Latin-1",
  stringsAsFactors = FALSE)
```

# Exploração dos dados

O Arquivo "RR2010.txt" contém as seguintes variáveis:

```{r}
RR10 %>% colnames()
```

Dessas, vamos pegar algumas para analisar:

```{r}
dados <- RR10 %>%
  select(`Faixa Etária`,
         `Faixa Remun Média (SM)`,
         `Escolaridade após 2005`,
         `Sexo Trabalhador`)
```


```{r, layout="l-body-outset"}
dados %>%
  glimpse()

dados %>%
  paged_table()
```


```{r, layout="l-body-outset"}
dados %>%
  filter(`Faixa Remun Média (SM)` != 99, `Escolaridade após 2005` != 99) %>%
  ggplot() +
  aes(
      fill = `Escolaridade após 2005` %>% as.factor(),
      y = `Escolaridade após 2005` %>% as.factor(), 
      x = `Faixa Remun Média (SM)`
  ) +
  geom_boxplot() +
  labs(
    title = "Distribuição da Remuneração Média por Escolaridade",
    subtitle = "",
    caption = "Fonte: Elaboração própria. Dados do RAIS",
    x = "Faixa de Remuneração Média",
    y = ""
  ) +
  scale_x_continuous(breaks = 0:11) +
  guides(fill = guide_legend(title = "Escolaridade", 
                             title.position = "top",
                             nrow = 2, byrow = TRUE,)) +
  theme_hc() +
  theme(
      plot.title = element_text(face = "bold", size = 14, hjust = 0, colour = "black",),
      plot.subtitle = element_text(face = "italic", size = 11, hjust = 0, colour = "grey30"),
      plot.caption = element_text(face = "italic", size = 6, margin = margin(t = 15), hjust = 1),
      legend.position = "top",
      legend.text = element_text(face = "plain", colour = "grey30", size = 9),
      legend.title = element_text(face = "bold", size = 10, hjust = 0.5),
      axis.title = element_text(size = 10, margin = margin(t = 10, r = 10)),
      axis.text = element_text(size = 8, margin = margin(t = 5, r = 5)),
      panel.grid.major.x = element_line(colour = gray(0.85),  size = 0.5),
      panel.grid.major.y = element_line(colour = gray(0.85),  size = 0.0)
  ) 
```